---
  fqdn: talaria
  env: test
  scheme: http

  primary:
    address: ":6200"
  health:
    address: ":6201"
  pprof:
    address: ":6202"
  control:
    address: ":6203"
  metric:
    address: ":6204"
    metricsOptions:
      namespace: "xmidt"
      subsystem: "talaria"

  log:
    file: "stdout"
    level: "debug"
    json: false

  device:
    manager:
      upgrader:
        handshakeTimeout: "10s"
      maxDevices: 2000
      deviceMessageQueueSize: 100
      pingPeriod: "45s"
      idlePeriod: "135s"
      requestTimeout: "15s"
    outbound:
      method: "POST"
      eventEndpoints:
        default: http://caduceus:6000/api/v3/notify
      requestTimeout: "125s"
      defaultScheme: "http"
      allowedSchemes:
        - "http"
        - "https"
      outboundQueueSize: 1000
      workerPoolSize: 100
      transport:
        maxIdleConns: 0
        maxIdleConnsPerHost: 100
        idleConnTimeout: "120s"
      clientTimeout: "160s"
      authKey: YXV0aEhlYWRlcg==
  inbound:
    authKey: YXV0aEhlYWRlcg==

  eventMap:
    default: http://caduceus:6000/api/v3/notify

  service:
    defaultScheme: http
    consul:
      client:
        address: "consul0:8500"
        scheme: "http"
        waitTime: "30s"
      disableGenerateID: true
      vnodeCount: 211
      watches:
        -
          service: "talaria"
          tags:
            - "dev"
            - "docker"
          passingOnly: true
        -
          service: "caduceus"
          tags:
            - "dev"
            - "docker"
          passingOnly: true
      registrations:
        -
          id: "talaria-0"
          name: "talaria"
          tags:
            - "dev"
            - "docker"
            - "stage=dev"
            - "flavor=docker"
          address: "http://talaria-0"
          scheme: "http"
          port: 6200
          checks:
            -
              checkID: "talaria-0:http"
              http: "http://talaria-0:6201/health"
              interval: "30s"
              deregisterCriticalServiceAfter: "70s"
