---
  fqdn: talaria
  env: test
  scheme: http

  primary:
    address: ":6200"
  health:
    address: ":6201"
  pprof:
    address: ":6202"
  control:
    address: ":6203"
  metric:
    address: ":6204"
    metricsOptions:
      namespace: "xmidt"
      subsystem: "talaria"

  log:
    file: "stdout"
    level: "debug"
    json: true

  device:
    manager:
      wrpSourceCheck:
        type: enforce
      upgrader:
        handshakeTimeout: "10s"
      maxDevices: 2000
      deviceMessageQueueSize: 100
      pingPeriod: "45s"
      idlePeriod: "135s"
      requestTimeout: "15s"
    rehasher:
      services:
        - talaria  
    outbound:
      method: "POST"
      eventEndpoints:
        default: http://caduceus:6000/api/v3/notify
      requestTimeout: "125s"
      defaultScheme: "http"
      allowedSchemes:
        - "http"
        - "https"
      outboundQueueSize: 1000
      workerPoolSize: 100
      transport:
        maxIdleConns: 0
        maxIdleConnsPerHost: 100
        idleConnTimeout: "120s"
      clientTimeout: "160s"
      authKey: dXNlcjpwYXNz
  inbound:
    authKey: dXNlcjpwYXNz

  eventMap:
    default: http://caduceus:6000/api/v3/notify

  jwtValidator:
    keys:
      Factory:
          uri: "http://themis:6500/keys/local"
      purpose: 0
      updateInterval: 24h 
  
  deviceAccessCheck:
    type: enforce
    checks:
      - 
        name: PartnerID
        deviceCredentialPath: partner-id
        op: contains
        wrpCredentialPath: PartnerIDs
        inversed: true
      - 
        name: Trusted Device
        deviceCredentialPath: trust
        op: "gt"
        inputValue: 999

  service:
    defaultScheme: http
    consul:
      client:
        address: "consul0:8500"
        scheme: "http"
        waitTime: "30s"
      disableGenerateID: true
      vnodeCount: 211
      watches:
        -
          service: "talaria"
          tags:
            - "stage=dev"
            - "flavor=docker"
          passingOnly: true
        -
          service: "caduceus"
          tags:
            - "stage=dev"
            - "flavor=docker"
          passingOnly: true

      registrations:
        -
          id: "talaria-0"
          name: "talaria"
          tags:
            - "stage=dev"
            - "flavor=docker"
          address: "http://talaria-0"
          scheme: "http"
          port: 6200
          checks:
            -
              checkID: "talaria-0:http"
              http: "http://talaria-0:6201/health"
              interval: "30s"
              deregisterCriticalServiceAfter: "70s"
