# Default values for xmitd-cloud.

simulator:
    image: xmidt/rdkb-simulator


#######################################################
#################### Child Charts #####################
#######################################################

caduceus:
  caduceus:
    image: xmidt/caduceus:0.2.1

scytale:
  scytale:
    image: xmidt/scytale:0.1.5
    fanout:
      endpoints: ["http://petasos:6400/api/v2/device/send"]

petasos:
  petasos:
    image: xmidt/petasos:0.1.4

talaria:
  talaria:
    image: xmidt/talaria:0.1.3

tr1d1um:
  tr1d1um:
    image: xmidt/tr1d1um:0.1.5