apiVersion: v1
data:
  tr1d1um.yaml: |
    fqdn: tr1d1um
    env: test
    scheme: http
    hooksScheme: http

    primary:
      address: ":6100"
    health:
      address: ":6101"
      options:
        - "PayloadsOverZero"
        - "PayloadsOverHundred"
        - "PayloadsOverThousand"
        - "PayloadsOverTenThousand"
      readTimeout: "15s"
      idleTimeout: "15s"
    pprof:
      address: ":6102"
      readTimeout: "15s"
      idleTimeout: "15s"
    metric:
      address: ":6103"
      metricsOptions:
        namespace: "webpa"
        subsystem: "tr1d1um"
      readTimeout: "15s"
      idleTimeout: "15s"
    log:
      file: "stdout"
      level: "INFO"
      json: false

    webhooksEnabled: false

    start:
      duration: 1
      apiPath: tr1d1um:6100/hooks

    waitForDns: 0

    aws:
      accessKey: "supbro"
      secretKey: "nahbro"
      env: local-dev
      sns:
        awsEndpoint: http://goaws:4100
        region: "us-east-1"
        topicArn: arn:aws:sns:us-east-1:000000000000:xmidt-local-caduceus
        urlPath: "/api/v2/aws/sns"

    authHeader: ["dXNlcjpwYXNz"]
    targetURL: http://scytale:6300
    # WRPSource: "dns:tr1d1um.xmidt.comcast.net"
    supportedServices:
      - "config"
    clientTimeout: "135s"
    respWaitTimeout: "129s"
    netDialerTimeout: "60s"
    requestRetryInterval: "2s"
    requestMaxRetries: 2
kind: ConfigMap
metadata:
  labels:
    app: xmidt-app
  name: tr1d1um-config
---
apiVersion: v1
kind: Service
metadata:
  name: tr1d1um-nodeport
spec:
  type: NodePort
  ports:
    - port: 6100
  selector:
    app: xmidt-app-tr1d1um
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    component: tr1d1um
    release: tr1d1um
  name: tr1d1um
spec:
  clusterIP: None
  ports:
    - name: http0
      port: 6100
      protocol: TCP
    - name: http1
      port: 6101
      protocol: TCP
    - name: http2
      port: 6102
      protocol: TCP
  selector:
    app: xmidt-app-tr1d1um
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tr1d1um
  labels:
    app: xmidt-app-tr1d1um
spec:
  selector:
    matchLabels:
      app: xmidt-app-tr1d1um
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  serviceName: xmidt-app
  template:
    metadata:
      labels:
        app: xmidt-app-tr1d1um
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - xmidt-app-tr1d1um
      volumes:
        - name: tr1d1um-config
          projected:
            sources:
              - configMap:
                  name: tr1d1um-config
                  items:
                    - key: tr1d1um.yaml
                      path: tr1d1um.yaml
                      mode: 0755
      securityContext:
        runAsNonRoot: false
        runAsUser: 999
        supplementalGroups: [999]
      containers:
        - image: {{ .Values.tr1d1um.image }}
          name: tr1d1um
          ports:
            - containerPort: 6100
              protocol: TCP
            - containerPort: 6101
              protocol: TCP
            - containerPort: 6102
              protocol: TCP
          volumeMounts:
            - name: tr1d1um-config
              mountPath: "/etc/tr1d1um"
              readOnly: true
