version: '3.8'
services:
  caduceus:
    image: xmidt/caduceus:${CADUCEUS_VERSION}
    ports:
      - "6000-6003:6000-6003"
    environment:
      - CONSUL_HOST=consul0:8500
      - ARGUS_HOST=http://argus:6600
    depends_on:
      - argus
    networks:
      - xmidt

  tr1d1um:
    image: xmidt/tr1d1um:${TR1D1UM_VERSION}
    environment:
      - CONSUL_HOST=consul0:8500
      - ARGUS_HOST=http://argus:6600
      - TRACING_PROVIDER_NAME=zipkin
      - TRACING_PROVIDER_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "6100-6103:6100-6103"
    depends_on:
      - argus
      - scytale
    networks:
      - xmidt

# Mark Talaria Services
  talaria-0: &talaria
    image: xmidt/talaria:${TALARIA_VERSION}
    environment:
      - CONSUL_HOST=consul0:8500
      - TRACING_PROVIDER_NAME=zipkin
      - TRACING_PROVIDER_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "6200-6204:6200-6204"
    depends_on:
      - consul0
      - themis
    networks:
      - xmidt
  talaria-1:
    <<: *talaria
    environment:
      - CONSUL_HOST=consul0:8500
      - TRACING_PROVIDER_NAME=zipkin
      - TRACING_PROVIDER_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "6210-6214:6200-6204"
  talaria-2:
    <<: *talaria
    environment:
      - CONSUL_HOST=consul1:8500
      - TRACING_PROVIDER_NAME=zipkin
      - TRACING_PROVIDER_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "6220-6224:6200-6204"
  scytale:
    image: xmidt/scytale:${SCYTALE_VERSION}
    environment:
      - CONSUL_HOST=consul0:8500
      - TRACING_PROVIDER_NAME=zipkin
      - TRACING_PROVIDER_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "6300-6303:6300-6303"
    depends_on:
      - petasos
    networks:
      - xmidt

# Mark petasos Services
  petasos: &petasos
    image: xmidt/petasos:${PETASOS_VERSION}
    environment:
      - CONSUL_HOST=consul0:8500
    ports:
    - "6400-6403:6400-6403"
    depends_on:
      - consul0
    networks:
      - xmidt

  themis:
    image: xmidt/themis:${THEMIS_VERSION}
    environment:
      - CONSUL_HOST=consul0:8500
      - TRACING_PROVIDER_NAME=zipkin
      - TRACING_PROVIDER_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "6500-6504:6500-6504"
    networks:
      - xmidt

  argus:
    image: xmidt/argus:${ARGUS_VERSION}
    environment:
      - "AWS_ENDPOINT=http://dynamodb:8000"
      - TRACING_PROVIDER_NAME=zipkin
      - TRACING_PROVIDER_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "6600-6603:6600-6603"
    depends_on:
      - dynamodb
    networks:
      - xmidt

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb
    ports:
      - "8000:8000"
    networks:
      - xmidt

  prometheus:
    image: prom/prometheus
    networks:
      - xmidt
    ports:
      - 9090:9090
    depends_on:
      - consul0
      - consul1
    volumes:
      - ./docFiles/prometheus.yml:/prometheus-data/prometheus.yml
    command:  --log.level=debug --config.file=/prometheus-data/prometheus.yml


# Mark rdkb-simulator Services
  simulator: &simulator
    image: xmidt/simulator:${SIMULATOR_VERSION}
    depends_on:
      - talaria-0
      - talaria-1
      - talaria-2
      - petasos
      - themis
    networks:
      - xmidt

# Mark Consul Definitions
  consul0:
    image: consul:latest
    container_name: consul0
    hostname: consul0
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
    networks:
      - xmidt
    volumes:
      - ./docFiles/consul-0.json:/consul.json
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0 -config-file consul.json"
  consul1:
    image: consul:latest
    container_name: consul1
    hostname: consul1
    ports:
      - 8401:8400
      - 8501:8500
      - 8601:8600
      - 8601:8600/udp
    networks:
      - xmidt
    depends_on:
      - consul0
    volumes:
      - ./docFiles/consul-1.json:/consul.json
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0 -config-file consul.json"

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - xmidt

  zipkin:
    image: openzipkin/zipkin 
    ports:
      - "9411:9411"
    networks:
      - xmidt

networks:
  xmidt:
